---
- name: add nginx user
  user: 
    name: "{{ user | default('nginx') }}"

- name: install nginx
  yum:
    name: nginx
    state: latest

- name: firewall
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify: restarted firewalld

- name: make service
  systemd:
    name: nginx
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: yes