version: '3'
services:
  ansible-container:
    container_name: ansible-container
    build: docker/ansible-container
    tty: true
    working_dir: "/var/data"
    volumes:
      - .:/var/data
    privileged: true
    command: /sbin/init
  
  centos7:
    container_name: centos7
    build: docker/centos7
    tty: true
    privileged: true
    command: /sbin/init